/*
 * Copyright 2006 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jvnet.jaxb.plugin.annotate_generated;

import com.sun.codemodel.*;
import com.sun.tools.xjc.BadCommandLineException;
import com.sun.tools.xjc.Options;
import com.sun.tools.xjc.model.CClassInfo;
import com.sun.tools.xjc.outline.ClassOutline;
import com.sun.tools.xjc.outline.Outline;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.jvnet.jaxb.xml.bind.Generated;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.xml.sax.ErrorHandler;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

class XjcAnnotateGeneratedPluginTest {

    private XjcAnnotateGeneratedPlugin plugin;

    @Mock
    private Outline outline;
    @Mock
    private Options options;
    @Mock
    private ErrorHandler errorHandler;
    @Mock
    private CClassInfo cClassInfo;

    private JDefinedClass implClass;

    @BeforeEach
    void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);

        JCodeModel codeModel = new JCodeModel();
        implClass = codeModel._class("TestGeneratedClass");
        ClassOutline classOutline = new TestableClassOutline(cClassInfo, implClass);
        when(outline.getClasses()).thenReturn((List) Collections.singletonList(classOutline));

        plugin = new XjcAnnotateGeneratedPlugin();
    }

    @Test
    void testGetOptionName() {
        assertEquals("XannotateGenerated", plugin.getOptionName());
    }

    @Test
    void testGetUsage() {
        String usage = plugin.getUsage();
        assertNotNull(usage);
        assertTrue(usage.contains("-XannotateGenerated"));
    }

    @Test
    void testRunWithDefaults() throws Exception {
        // Defaults: addGeneratedAnnotation=true, suppresFBWarnings=false, suppressWarnings=true
        plugin.run(outline, options, errorHandler);

        assertTrue(hasAnnotation(implClass, org.jvnet.jaxb.xml.bind.Generated.class),
            "Should have @Generated by default");
        assertTrue(hasAnnotation(implClass, java.lang.SuppressWarnings.class),
            "Should have @SuppressWarnings by default");
        assertFalse(hasAnnotation(implClass, XjcAnnotateGeneratedPlugin.SUPPRESS_FBWARNINGS_FQ_CLASS),
            "Should NOT have @SuppressFBWarnings by default");
    }

    @Test
    void testRunWithAllDisabled() throws Exception {
        // Set all to FALSE via parsing arguments
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addGeneratedAnnotation=FALSE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressFBWarnings=FALSE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressWarnings=FALSE"}, 0);

        plugin.run(outline, options, errorHandler);

        assertFalse(hasAnnotation(implClass, Generated.class), "Should not have @Generated"); // Note: class name depends on your classpath
        // We check if the annotation list is empty or at least doesn't contain our targets
        long annotationCount = implClass.annotations().size();
        assertEquals(0, annotationCount, "No annotations should be applied when all are disabled");
    }

    @Test
    void testRunWithAllEnabled() throws Exception {
        // Set all to TRUE via parsing arguments
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addGeneratedAnnotation=TRUE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressFBWarnings=TRUE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressWarnings=TRUE"}, 0);

        plugin.run(outline, options, errorHandler);

        assertTrue(hasAnnotation(implClass, org.jvnet.jaxb.xml.bind.Generated.class),
            "Should have @Generated by default");
        assertTrue(hasAnnotation(implClass, XjcAnnotateGeneratedPlugin.SUPPRESS_FBWARNINGS_FQ_CLASS),
            "Should have @SuppressFBWarnings");
        assertTrue(hasAnnotation(implClass, java.lang.SuppressWarnings.class),
            "Should have @SuppressWarnings by default");
        Map<String, JAnnotationValue> annotationMembers = getAnnotation(implClass).get().getAnnotationMembers();
        assertEquals("all", annotationMembers.get("value").toString());
    }

    @Test
    void testOnlyGeneratedEnabled() throws Exception {
        // Set all to TRUE via parsing arguments
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addGeneratedAnnotation=TRUE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressFBWarnings=FALSE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressWarnings=FALSE"}, 0);

        plugin.run(outline, options, errorHandler);

        assertTrue(hasAnnotation(implClass, org.jvnet.jaxb.xml.bind.Generated.class),
            "Should have @Generated");
        assertFalse(hasAnnotation(implClass, XjcAnnotateGeneratedPlugin.SUPPRESS_FBWARNINGS_FQ_CLASS),
            "Should have @SuppressFBWarnings");
        assertFalse(hasAnnotation(implClass, java.lang.SuppressWarnings.class),
            "Should have @SuppressWarnings");
    }

    @Test
    void testOnlySupressFBWarningsEnabled() throws Exception {
        // Set all to TRUE via parsing arguments
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addGeneratedAnnotation=FALSE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressFBWarnings=TRUE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressWarnings=FALSE"}, 0);

        plugin.run(outline, options, errorHandler);

        assertFalse(hasAnnotation(implClass, org.jvnet.jaxb.xml.bind.Generated.class),
            "Should not have @Generated");
        assertTrue(hasAnnotation(implClass, XjcAnnotateGeneratedPlugin.SUPPRESS_FBWARNINGS_FQ_CLASS),
            "Should have @SuppressFBWarnings");
        assertFalse(hasAnnotation(implClass, java.lang.SuppressWarnings.class),
            "Should not have @SuppressWarnings");
    }

    @Test
    void testSupressWarningsEnabled() throws Exception {
        // Set all to TRUE via parsing arguments
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addGeneratedAnnotation=FALSE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressFBWarnings=FALSE"}, 0);
        plugin.parseArgument(options, new String[]{"-XannotateGenerated:addSuppressWarnings=TRUE"}, 0);

        plugin.run(outline, options, errorHandler);

        assertFalse(hasAnnotation(implClass, XjcAnnotateGeneratedPlugin.SUPPRESS_FBWARNINGS_FQ_CLASS),
            "Should not have @SuppressFBWarnings");
        assertFalse(hasAnnotation(implClass, org.jvnet.jaxb.xml.bind.Generated.class),
            "Should not have @Generated");
        assertTrue(hasAnnotation(implClass, java.lang.SuppressWarnings.class),
            "Should have @SuppressWarnings by default");
        Map<String, JAnnotationValue> annotationMembers = getAnnotation(implClass).get().getAnnotationMembers();
        assertEquals("all", annotationMembers.get("value").toString());
    }

    @Test
    void testParseArgumentCustomGeneratedAnnotationClass() throws BadCommandLineException {
        String arg = "-XannotateGenerated:customGeneratedAnnotationClass=my.CustomGeneratedAnnotationClass";
        assertEquals(1, plugin.parseArgument(options, new String[]{arg}, 0));

        plugin.run(outline, options, errorHandler);

        assertTrue(hasAnnotation(implClass, "my.CustomGeneratedAnnotationClass"), "my.CustomGeneratedAnnotationClass should have been attached");
    }

    @Test
    void testParseArgumentNotMatching() throws BadCommandLineException {
        assertEquals(0, plugin.parseArgument(options, new String[]{"-Xunknown"}, 0));
    }

    private boolean hasAnnotation(JDefinedClass clazz, Class<?> annotationClass) {
        return hasAnnotation(clazz, annotationClass.getName());
    }

    private boolean hasAnnotation(JDefinedClass clazz, String annotationClass) {
        return clazz.annotations().stream()
            .anyMatch(anno -> anno.getAnnotationClass().fullName().equals(annotationClass));
    }

    private Optional<JAnnotationUse> getAnnotation(JDefinedClass clazz) {
        return clazz.annotations().stream()
            .filter(anno -> anno.getAnnotationClass().fullName().equals("java.lang.SuppressWarnings"))
            .findFirst();
    }

    public static class TestableClassOutline extends ClassOutline {
        public TestableClassOutline(CClassInfo target, JDefinedClass implClass) {
            super(target, null, null, implClass);
        }

        @Override
        public Outline parent() {
            return null;
        }
    }
}
